Repository codestates-seb/seb43_main_001, pull requests merged in 2023-05, with the labels that each got.

#12 comment:불필요한 코드들 제거 및 정리
  client/src/store/slice/themeSlice.ts
Labels: 🎨HTML&CSS

#17 refactor: icons 설정#16
  client/src/components/common/icons.tsx
Labels: 🛠Refector, ⚙Setting

#23 design:헤더 레이아웃 구현
  client/src/components/common/button.style.tsx
  client/src/components/common/button.tsx
  client/src/constants/index.ts
  client/src/layout/header/Hamburger.style.tsx
  client/src/layout/header/Hamburger.tsx
  client/src/layout/header/Header.style.tsx
  client/src/layout/header/Header.tsx
  client/src/layout/header/Toggle.style.tsx
  client/src/layout/header/Toggle.tsx
  client/src/style/theme.ts
Labels: 🔥Feature, 🎨HTML&CSS

#25 design:로그인 레이아웃 구현
  client/src/components/Login/LoginContainer.style.tsx
  client/src/components/Login/LoginContainer.tsx
  client/src/components/Login/OAuthBtn.style.tsx
  client/src/components/Login/OAuthBtn.tsx
  client/src/pages/Login.tsx
Labels: 🎨HTML&CSS

#26 design:header 레이아웃 최종 수정
  client/package-lock.json
  client/package.json
  client/public/assets/icon/moon.svg
  client/public/assets/icon/sun.svg
  client/src/components/common/icons.tsx
  client/src/constants/index.ts
  client/src/layout/header/Hamburger.style.tsx
  client/src/layout/header/Hamburger.tsx
  client/src/layout/header/Header.style.tsx
  client/src/layout/header/Header.tsx
  client/src/layout/header/NavLink.style.tsx
  client/src/layout/header/NavLink.tsx
  client/src/layout/main/Main.style.tsx
  client/src/layout/main/Main.tsx
  client/src/style/GlobalStyle.ts
Labels: 🔥Feature, 🎨HTML&CSS

#24 API 명세서 작성
  server/build.gradle
  server/src/main/java/main001/server/audit/BaseTimeEntity.java
  server/src/main/java/main001/server/domain/portfolio/dto/PortfolioDto.java
  server/src/main/java/main001/server/domain/portfoliocomment/controller/PortfolioCommentController.java
  server/src/main/java/main001/server/domain/portfoliocomment/dto/PortfolioCommentDto.java
  server/src/main/java/main001/server/domain/portfoliocomment/entity/PortfolioComment.java
  server/src/main/java/main001/server/domain/portfoliocomment/mapper/PortfolioCommentMapper.java
  server/src/main/java/main001/server/domain/user/dto/UserDto.java
  server/src/main/java/main001/server/domain/usercomment/dto/UserCommentDto.java
  server/src/main/java/main001/server/domain/usercomment/mapper/UserCommentMapper.java
  server/src/test/java/main001/server/domain/portfolio/controller/PortfolioControllerTest.java
  server/src/test/java/main001/server/domain/portfoliocomment/PortfolioCommentControllerTest.java
  server/src/test/java/main001/server/domain/portfoliocomment/PortfolioCommentRepositoryTest.java
  server/src/test/java/main001/server/domain/user/controller/UserControllerRestDocsTest.java
  server/src/test/java/main001/server/domain/usercomment/UserCommentControllerTest.java
Labels: 📃Docs, 🛠Refector

#27 design: global 스타일 속성 추가
  client/src/components/common/button.style.tsx
  client/src/layout/header/NavLink.style.tsx
  client/src/pages/Detail.tsx
  client/src/store/slice/themeSlice.ts
  client/src/style/GlobalStyle.ts
Labels: 🎨HTML&CSS

#30 design: footer 컴포넌트 구현
  client/src/layout/footer/Footer.style.tsx
  client/src/layout/footer/Footer.tsx
Labels: 🎨HTML&CSS

#31 fix:헤더 배경 transparent 현상 해결
  client/src/layout/header/Header.style.tsx
  client/src/layout/header/NavLink.style.tsx
Labels: 🐞BugFix

#37 feat: Detail Page 및 상태 유지 기능 추가
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Detail/Comment.style.tsx
  client/src/components/Detail/Comment.tsx
  client/src/components/Detail/CommentItem.style.tsx
  client/src/components/Detail/CommentItem.tsx
  client/src/components/Detail/Description.style.tsx
  client/src/components/Detail/Description.tsx
  client/src/components/Detail/DetailTitle.style.tsx
  client/src/components/Detail/DetailTitle.tsx
  client/src/components/Detail/ProjectContent.style.tsx
  client/src/components/Detail/ProjectContent.tsx
  client/src/components/Detail/ProjectImg.style.tsx
  client/src/components/Detail/ProjectImg.tsx
  client/src/components/common/YellowTag.style.tsx
  client/src/components/common/YellowTag.tsx
  client/src/hooks/reduxHook.ts
  client/src/index.tsx
  client/src/layout/header/Header.tsx
  client/src/layout/header/Toggle.style.tsx
  client/src/layout/header/Toggle.tsx
  client/src/layout/main/Main.style.tsx
  client/src/pages/Detail.style.tsx
  client/src/pages/Detail.tsx
  client/src/store/index.ts
  client/src/store/slice/themeSlice.ts
  client/src/style/theme.ts
Labels: 🔥Feature, 🎨HTML&CSS

#38 design: 카드 컴포넌트 추가
  client/src/components/common/Card.style.tsx
  client/src/components/common/Card.tsx
  client/src/style/theme.ts
Labels: 🎨HTML&CSS

#43 design: Not Found 페이지 구현
  client/src/pages/NotFound.style.ts
  client/src/pages/NotFound.tsx
  client/src/router.tsx
Labels: 🔥Feature, 🎨HTML&CSS

#44 design:Detail comment 부분 추가 수정
  client/src/components/Detail/Comment.style.tsx
  client/src/components/Detail/Comment.tsx
  client/src/components/Detail/CommentItem.style.tsx
  client/src/components/Detail/CommentItem.tsx
  client/src/components/Detail/ProjectImg.style.tsx
  client/src/components/Detail/ProjectImg.tsx
  client/src/components/Detail/mock.ts
  client/src/layout/header/Header.style.tsx
  client/src/pages/Detail.style.tsx
Labels: 🎨HTML&CSS

#46 design: 포트폴리오 작성 페이지 추가
  client/package-lock.json
  client/package.json
  client/src/components/Portfolio/DetailBox.style.tsx
  client/src/components/Portfolio/DetailBox.tsx
  client/src/components/Portfolio/ImgBox.style.tsx
  client/src/components/Portfolio/ImgBox.tsx
  client/src/components/Portfolio/NewPortfolioContainer.style.tsx
  client/src/components/Portfolio/NewPortfolioContainer.tsx
  client/src/components/Portfolio/TagBox.style.tsx
  client/src/components/Portfolio/TagBox.tsx
  client/src/components/Portfolio/TextBox.style.tsx
  client/src/components/Portfolio/TextBox.tsx
  client/src/components/Portfolio/TextareaBox.style.tsx
  client/src/components/Portfolio/TextareaBox.tsx
  client/src/components/Portfolio/UserBox.style.tsx
  client/src/components/Portfolio/UserBox.tsx
  client/src/pages/Portfolio.style.tsx
  client/src/pages/Portfolio.tsx
  client/src/router.tsx
Labels: 🔥Feature, 🎨HTML&CSS

#48 design:5월8일 UI 전체 공통 수정
  .github/ISSUE_TEMPLATE/be-이슈-템플릿.md
  client/src/components/Detail/Comment.style.ts
  client/src/components/Detail/Comment.tsx
  client/src/components/Detail/CommentItem.style.ts
  client/src/components/Detail/Description.style.ts
  client/src/components/Detail/DetailTitle.style.ts
  client/src/components/Detail/ProjectContent.style.ts
  client/src/components/Detail/ProjectImg.style.ts
  client/src/components/Home/Banner.tsx
  client/src/components/Portfolio/NewPortfolioContainer.style.tsx
  client/src/components/User/UserBasicInfo.tsx
  client/src/components/User/UserInfo.tsx
  client/src/components/common/YellowTag.style.tsx
  client/src/components/common/button.style.tsx
  client/src/components/common/button.tsx
  client/src/layout/header/Header.tsx
  client/src/pages/Detail.style.ts
  client/src/pages/NotFound.style.ts
  client/src/style/GlobalStyle.ts
Labels: 🎨HTML&CSS

#49 fix:포트폴리오 작성 페이지, react quill 기능 수정 및 태그 수정
  client/src/components/Portfolio/DetailBox.tsx
  client/src/components/Portfolio/NewPortfolioContainer.style.tsx
  client/src/components/Portfolio/TagBox.tsx
  client/src/style/GlobalStyle.ts
Labels: 🐞BugFix

#51 design: Feedback 수정 및 CRUD 추가
  client/src/components/User/Feedback.style.ts
  client/src/components/User/Feedback.tsx
  client/src/components/User/FeedbackContainer.style.ts
  client/src/components/User/FeedbackContainer.tsx
  client/src/components/User/Portfolio.style.ts
  client/src/components/User/Portfolio.tsx
  client/src/components/User/UserBasicInfo.style.ts
  client/src/components/User/UserBasicInfo.tsx
  client/src/components/User/UserDetailInfo.style.ts
  client/src/components/User/UserDetailInfo.tsx
  client/src/components/User/UserEditForm.style.ts
  client/src/components/User/UserInfo.style.ts
  client/src/components/User/UserInfo.tsx
  client/src/components/common/Button.tsx
  client/src/components/common/Card.style.ts
  client/src/pages/User.style.ts
Labels: 🎨HTML&CSS

#52 refactor: Home, footer 컴포넌트 수정
  client/src/components/Home/Banner.style.ts
  client/src/components/Home/Banner.tsx
  client/src/components/Home/Search.style.ts
  client/src/components/Home/Sort.tsx
  client/src/components/common/Card.style.ts
  client/src/components/common/Card.tsx
  client/src/layout/footer/Footer.style.ts
  client/src/layout/main/Main.style.tsx
  client/src/pages/Home.style.ts
Labels: 🐞BugFix, 🎨HTML&CSS

#53 refactor: 코드 정리
  client/src/components/Login/LoginContainer.style.tsx
  client/src/components/Login/LoginContainer.tsx
  client/src/components/Portfolio/DetailBox.tsx
Labels: 🎨HTML&CSS, 🛠Refector

#54 design: 버튼 크기 등 CSS 수정
  client/src/components/User/Feedback.style.ts
  client/src/components/User/Feedback.tsx
  client/src/components/User/FeedbackContainer.style.ts
  client/src/components/User/Portfolio.style.ts
  client/src/components/User/Portfolio.tsx
  client/src/components/User/UserBasicInfo.style.ts
  client/src/components/User/UserBasicInfo.tsx
  client/src/components/User/UserEditForm.style.ts
  client/src/components/User/UserEditForm.tsx
  client/src/components/User/UserInfo.style.ts
  client/src/components/User/mock.ts
Labels: 🎨HTML&CSS

#58 refactor: 포트폴리오 수정 페이지 분리
  client/src/components/Portfolio/DetailBox.style.ts
  client/src/components/Portfolio/ImgBox.style.ts
  client/src/components/Portfolio/NewPortfolioContainer.tsx
  client/src/components/Portfolio/PortfolioContainer.style.ts
  client/src/components/Portfolio/PortfolioContainer.tsx
  client/src/components/Portfolio/TagBox.style.ts
  client/src/components/Portfolio/TextBox.style.ts
  client/src/components/Portfolio/TextareaBox.style.ts
  client/src/components/Portfolio/UserBox.style.ts
  client/src/pages/EditPortfolio.style.ts
  client/src/pages/EditPortfolio.tsx
  client/src/pages/NewPortfolio.style.ts
  client/src/pages/NewPortfolio.tsx
  client/src/pages/Portfolio.tsx
  client/src/router.tsx
Labels: 🛠Refector

#59 fix: 모바일과 데스크탑 브라우저에서 input이 다르게 보이는 버그 수정
  client/src/components/Home/Search.style.ts
  client/src/components/Home/Search.tsx
Labels: 🐞BugFix

#61 feat: 상세 페이지 UI 수정 및 react-query 초기 셋팅
  client/package-lock.json
  client/package.json
  client/src/components/Detail/Comment.style.ts
  client/src/components/Detail/Comment.tsx
  client/src/components/Detail/CommentItem.style.ts
  client/src/components/Detail/CommentItem.tsx
  client/src/components/Detail/Description.style.ts
  client/src/components/Detail/Description.tsx
  client/src/components/Detail/DetailTitle.style.ts
  client/src/components/Detail/DetailTitle.tsx
  client/src/components/Detail/LikeBtn.style.ts
  client/src/components/Detail/LikeBtn.tsx
  client/src/components/Detail/ProjectContent.tsx
  client/src/components/Detail/ProjectImg.tsx
  client/src/index.tsx
  client/src/layout/header/Header.tsx
  client/src/layout/header/NavLink.tsx
  client/src/pages/Detail.tsx
Labels: 🎨HTML&CSS, ⚙Setting

#64 feat: 작성한 피드백 조회 추가
  client/src/components/User/Feedback.style.ts
  client/src/components/User/Feedback.tsx
  client/src/components/User/FeedbackContainer.style.ts
  client/src/components/User/FeedbackContainer.tsx
  client/src/components/User/UserBasicInfo.tsx
  client/src/components/User/UserDetailInfo.tsx
  client/src/components/User/UserEditForm.style.ts
  client/src/components/User/UserEditForm.tsx
  client/src/components/User/UserInfo.style.ts
  client/src/components/User/UserInfo.tsx
  client/src/components/User/mock.ts
Labels: 🎨HTML&CSS

#67 design: AddEmail 페이지 레이아웃 구현
  client/src/pages/AddEmail.style.ts
  client/src/pages/AddEmail.tsx
  client/src/router.tsx
Labels: 🎨HTML&CSS

#69 feat: redux-persist를 이용한 로그인,토큰 상태관리 기능 구현
  client/src/store/index.ts
  client/src/store/slice/loginSlice.ts
Labels: 🔥Feature

#73 feat: 로그인 시, token 받기 기능 구현
  client/src/components/Login/LoginContainer.tsx
  client/src/store/slice/loginSlice.ts
Labels: 📬API, 🔥Feature

#74 feat: Oauth 버튼 기능 추가
  client/src/components/Login/OAuthBtn.tsx
Labels: 🔥Feature

#75 feat: Detail 페이지 path 경로에 id 추가
  client/src/components/Home/Banner.tsx
  client/src/components/common/Card.tsx
  client/src/router.tsx
Labels: 🔥Feature

#76 feat:헤더 로그인에 따른 기능 추가
  client/src/components/Detail/Comment.tsx
  client/src/components/Detail/CommentItem.style.ts
  client/src/components/Detail/CommentItem.tsx
  client/src/components/Detail/DetailTitle.tsx
  client/src/components/Detail/LikeBtn.style.ts
  client/src/components/Detail/ProjectContent.tsx
  client/src/components/Detail/mock.ts
  client/src/hooks/useDetailPageComment.ts
  client/src/layout/header/Header.style.tsx
  client/src/layout/header/Header.tsx
  client/src/layout/header/NavLink.tsx
  client/src/pages/Detail.tsx
  client/src/router.tsx
  client/src/types/index.ts
Labels: 📬API, 🎨HTML&CSS

#80 feat: 유저 정보 조회/수정 ajax 적용(수정필요)
  client/src/components/User/CommentContainer.style.ts
  client/src/components/User/CommentContainer.tsx
  client/src/components/User/CommentItem.style.ts
  client/src/components/User/CommentItem.tsx
  client/src/components/User/Feedback.tsx
  client/src/components/User/FeedbackContainer.tsx
  client/src/components/User/UserBasicInfo.tsx
  client/src/components/User/UserDetailInfo.tsx
  client/src/components/User/UserEditForm.tsx
  client/src/components/User/UserInfo.tsx
  client/src/components/User/data/data.json
  client/src/hooks/useUserInfo.ts
  client/src/pages/User.tsx
  client/src/router.tsx
  client/src/store/index.ts
  client/src/store/slice/userInfoSlice.ts
Labels: 📬API, 🔥Feature

#86 feat: 로그인 성공 시 토큰 받아오는 기능 추가
  client/src/components/Home/Banner.tsx
  client/src/components/Home/Search.tsx
  client/src/components/Home/Sort.tsx
  client/src/components/Home/db.json
  client/src/components/Home/db.test.json
  client/src/components/Portfolio/TextBox.tsx
  client/src/components/common/Card.tsx
  client/src/pages/Home.style.ts
  client/src/pages/Home.tsx
Labels: 🔥Feature

#88 feat: 이메일 추가 페이지: 이메일 전송 기능 추가
  client/src/pages/AddEmail.style.ts
  client/src/pages/AddEmail.tsx
Labels: 📬API, 🔥Feature

#95 feat:react-query를 적용한 AJAX 기능 구현(추가 수정 필요)
  client/package-lock.json
  client/package.json
  client/src/api/client.ts
  client/src/components/Detail/Comment.tsx
  client/src/components/Detail/Description.tsx
  client/src/components/Detail/DetailTitle.tsx
  client/src/constants/index.ts
  client/src/hooks/useDetailPageComment.ts
  client/src/hooks/useGetPortfolio.ts
  client/src/hooks/useGetPortfolioComment.ts
  client/src/hooks/usePatchPortfolioComment.ts
  client/src/hooks/usePostPortfolioComment.ts
  client/src/router.tsx
  client/src/store/slice/loginSlice.ts
  client/src/types/index.ts
  client/src/utils/getAccessToken.ts
  client/src/utils/getUserIdFromAccessToken.ts
Labels: 📬API, 🔥Feature

#103 fix: 구글 로그인 버튼 onClick 함수 수정
  client/src/components/Login/LoginContainer.tsx
Labels: 🐞BugFix

#104 fix: 구글 로그인 url 수정
  client/src/components/Login/LoginContainer.tsx
Labels: 📬API, 🐞BugFix

#118 feat:상세페이지 AJAX 요청 level 1 완료
  client/src/api/client.ts
  client/src/components/Detail/Comment.tsx
  client/src/components/Detail/CommentItem.style.ts
  client/src/components/Detail/CommentItem.tsx
  client/src/components/Detail/Description.tsx
  client/src/components/Detail/DetailTitle.style.ts
  client/src/components/Detail/DetailTitle.tsx
  client/src/components/Detail/ProjectContent.tsx
  client/src/components/Detail/ProjectImg.tsx
  client/src/hooks/useDeletePortfolioComment.ts
  client/src/hooks/useGetPortfolio.ts
  client/src/hooks/usePatchPortfolioComment.ts
  client/src/hooks/usePostPortfolioComment.ts
  client/src/layout/header/Header.tsx
  client/src/pages/Detail.style.ts
  client/src/pages/Detail.tsx
  client/src/types/index.ts
Labels: 📬API, 🔥Feature

#122 feat:API TokenClient 수정 및 UI 수정
  client/src/api/client.ts
  client/src/components/Detail/CommentItem.tsx
  client/src/components/Detail/DetailTitle.style.ts
  client/src/components/Detail/DetailTitle.tsx
  client/src/hooks/useDeletePortfolioComment.ts
  client/src/pages/Home.tsx
  client/src/utils/getUserIdFromAccessToken.ts
Labels: 📬API

#124 feat:포트폴리오 생성, 수정 페이지 AJAX 구현
  client/package-lock.json
  client/package.json
  client/src/api/client.ts
  client/src/components/Portfolio/DetailBox.style.ts
  client/src/components/Portfolio/DetailBox.tsx
  client/src/components/Portfolio/ImgBox.tsx
  client/src/components/Portfolio/PortfolioContainer.tsx
  client/src/components/Portfolio/TextBox.tsx
  client/src/components/Portfolio/TextareaBox.tsx
  client/src/components/Portfolio/UserBox.tsx
  client/src/hooks/usePatchPortfolio.ts
  client/src/hooks/usePostPortfolio.ts
  client/src/pages/EditPortfolio.tsx
  client/src/pages/NewPortfolio.tsx
  client/src/router.tsx
  client/src/types/index.ts
Labels: 📬API, 🔥Feature, 🛠Refector

#126 rename: UserInfo -> UserProfile로 네이밍 수정
  client/src/components/Portfolio/PortfolioContainer.tsx
  client/src/components/Portfolio/UserBox.tsx
  client/src/pages/EditPortfolio.tsx
  client/src/pages/NewPortfolio.tsx
Labels: 🐞BugFix

#134 feat: 로그인 유무에 따른 페이지 접근 제한 기능 추가
  client/src/router.tsx
  client/src/utils/loaderAuth.ts
Labels: 🔥Feature

#136 feat: GeneraLayout에 Outlet 추가
  client/src/layout/GeneraLayout.tsx
Labels: 🔥Feature

#137 feat: 무한스크롤 및 정렬 기능 추가
  client/src/api/client.ts
  client/src/components/Home/Banner.tsx
  client/src/components/Home/Search.tsx
  client/src/components/Home/Sort.tsx
  client/src/components/Home/db.json
  client/src/components/Home/db.test.json
  client/src/components/common/Card.style.ts
  client/src/components/common/Card.tsx
  client/src/hooks/useGetAllPortfolio.ts
  client/src/hooks/useGetSearchPortfolio.ts
  client/src/pages/Home.style.ts
  client/src/pages/Home.tsx
  client/src/types/index.ts
Labels: 📬API, 🔥Feature

#145 fix: Login 전역 상태 token값 저장 기능 제거 및 관련 오류 수정
  client/src/pages/EditPortfolio.tsx
  client/src/pages/NewPortfolio.tsx
  client/src/store/slice/loginSlice.ts
Labels: 🐞BugFix

#148 feat: 깃허브 로그인시 이메일 추가 기능 구현 및 API 수정
  client/src/api/client.ts
  client/src/components/Login/LoginContainer.tsx
  client/src/pages/AddEmail.tsx
Labels: 📬API, 🔥Feature

#149 fix:좋아요,로그아웃,토큰 버그 수정
  client/src/api/client.ts
  client/src/components/Detail/LikeBtn.style.ts
  client/src/components/Detail/LikeBtn.tsx
  client/src/hooks/useLikeBtn.ts
  client/src/layout/header/Header.style.tsx
  client/src/layout/header/Header.tsx
Labels: 📬API, 🐞BugFix, 🎨HTML&CSS

#152 feat: UserPortfolios 무한스크롤 구현
  client/src/api/client.ts
  client/src/components/User/CommentContainer.style.ts
  client/src/components/User/CommentContainer.tsx
  client/src/components/User/CommentItem.style.ts
  client/src/components/User/CommentItem.tsx
  client/src/components/User/Portfolio.style.ts
  client/src/components/User/Portfolio.tsx
  client/src/components/User/UserBasicInfo.style.ts
  client/src/components/User/UserBasicInfo.tsx
  client/src/components/User/UserEditForm.style.ts
  client/src/components/User/UserEditForm.tsx
  client/src/components/User/UserInfo.tsx
  client/src/components/common/ConfirmationModal.style.ts
  client/src/components/common/ConfirmationModal.tsx
  client/src/hooks/useDeleteUserProfile.ts
  client/src/hooks/useGetUserPortfolios.ts
  client/src/hooks/useGetUserProfile.ts
  client/src/hooks/usePatchUserProfile.ts
  client/src/hooks/usePostUserComment.ts
  client/src/store/index.ts
  client/src/store/slice/editUserProfileSlice.ts
  client/src/store/slice/modalSlice.ts
  client/src/types/index.ts
Labels: 📬API, 🐞BugFix, 🔥Feature

#161 feat:좋아요 기능,헤더 이미지 기능 수정
  client/src/api/client.ts
  client/src/components/Detail/DetailTitle.tsx
  client/src/components/Detail/LikeBtn.tsx
  client/src/components/Detail/ProjectImg.style.ts
  client/src/components/Detail/ProjectImg.tsx
  client/src/components/common/Loading.style.ts
  client/src/constants/index.ts
  client/src/hooks/useIncreasePageView.ts
  client/src/hooks/useLikeBtn.ts
  client/src/index.tsx
  client/src/layout/header/Header.tsx
  client/src/pages/Detail.tsx
  client/src/types/index.ts
  client/src/utils/IncreasePageView.ts
  client/src/utils/getAccessToken.ts
  client/src/utils/hasViewedPageInSession.ts
  client/src/utils/markPageViewedInSession.ts
Labels: 📬API, 🐞BugFix, 🔥Feature

#162 feat: 검색기능 및 토스트 추가
  client/package-lock.json
  client/package.json
  client/src/api/client.ts
  client/src/components/Home/Search.tsx
  client/src/components/common/Card.tsx
  client/src/hooks/useGetAllPortfolio.ts
  client/src/hooks/useGetPortfolioList.ts
  client/src/hooks/useGetSearchPortfolio.ts
  client/src/layout/GeneraLayout.tsx
  client/src/pages/Home.tsx
Labels: 📬API, 🔥Feature

#172 feat: 유저 댓글 임시 Auth 기능 추가, Link 아이콘 표시 변경
  client/src/components/User/CommentContainer.tsx
  client/src/components/User/CommentItem.style.ts
  client/src/components/User/CommentItem.tsx
  client/src/components/User/Portfolio.style.ts
  client/src/components/User/Portfolio.tsx
  client/src/components/User/UserBasicInfo.style.ts
  client/src/components/User/UserBasicInfo.tsx
  client/src/components/User/UserInfo.style.ts
  client/src/components/User/UserInfo.tsx
  client/src/components/common/Button.style.ts
  client/src/types/index.ts
Labels: 🔥Feature

#173 fix: 카드 소개글 줄바꿈 처리
  client/src/components/common/Card.style.ts
Labels: 🐞BugFix

#174 feat: 상세페이지 수정 및 삭제 기능 추가
  client/src/api/client.ts
  client/src/components/Detail/DetailTitle.tsx
  client/src/hooks/useDeletePortfolio.ts
  client/src/pages/Detail.tsx
Labels: 📬API, 🔥Feature

#175 feat: 문의하기 모달 추가
  client/src/layout/footer/Footer.tsx
  client/src/layout/footer/HelpModal.style.ts
  client/src/layout/footer/HelpModal.tsx
Labels: 🔥Feature, 🎨HTML&CSS

#177 feat: email&pw 로그인 기능 추가 및 화면 레이아웃 변경
  client/src/api/client.ts
  client/src/components/Login/LoginContainer.style.tsx
  client/src/components/Login/LoginContainer.tsx
  client/src/components/Login/OAuthBtn.style.tsx
  client/src/components/Login/OAuthBtn.tsx
  client/src/hooks/usePostUserLogin.ts
  client/src/types/index.ts
Labels: 📬API, 🔥Feature, 🎨HTML&CSS

#182 fix:종합 에러 수정
  client/public/index.html
  client/src/api/client.ts
  client/src/components/Detail/Description.style.ts
  client/src/components/Detail/DetailTitle.style.ts
  client/src/components/Detail/DetailTitle.tsx
  client/src/components/Detail/ProjectContent.style.ts
  client/src/components/Detail/ProjectImg.style.ts
  client/src/components/Detail/ProjectImg.tsx
  client/src/components/common/Card.style.ts
  client/src/hooks/useGetPortfolioList.ts
  client/src/layout/header/Header.tsx
  client/src/pages/Detail.tsx
  client/src/style/GlobalStyle.ts
  client/src/types/index.ts
Labels: 🐞BugFix

#183 fix: 회원정보 수정 때 다른 유저의 정보가 나타나는 버그 수정
  client/src/components/User/CommentContainer.tsx
  client/src/components/User/Portfolio.style.ts
  client/src/components/User/UserBasicInfo.tsx
  client/src/components/User/UserEditForm.style.ts
  client/src/components/User/UserInfo.tsx
  client/src/components/User/data/data.json
  client/src/pages/User.tsx
Labels: 🐞BugFix, 🎨HTML&CSS

#190 fix: 헤더에서 토큰을 받아오는 방식으로 email 로그인 수정
  client/src/hooks/usePostUserLogin.ts
Labels: 📬API, 🐞BugFix

#195 design: header 로고 추가
  client/public/assets/logo/silmul_logo.svg
  client/src/components/common/icons.tsx
  client/src/layout/header/Header.style.tsx
  client/src/layout/header/Header.tsx
Labels: 🎨HTML&CSS

#199 feat: 댓글 삭제 확인 과정 추가
  client/src/components/User/CommentItem.style.ts
  client/src/components/User/CommentItem.tsx
  client/src/components/User/UserBasicInfo.tsx
  client/src/components/common/ConfirmationModal.style.ts
Labels: 🔥Feature

#201 feat: Tag 자동완성 기능 및 Editor 컴포넌트화
  client/src/components/Detail/ProjectContent.tsx
  client/src/components/Portfolio/DetailBox.tsx
  client/src/components/Portfolio/Editor.style.ts
  client/src/components/Portfolio/Editor.tsx
  client/src/components/Portfolio/PortfolioContainer.tsx
  client/src/components/Portfolio/TagBox.style.ts
  client/src/components/Portfolio/TagBox.tsx
  client/src/components/Portfolio/TextBox.tsx
  client/src/components/Portfolio/TextareaBox.style.ts
  client/src/components/Portfolio/TextareaBox.tsx
  client/src/hooks/usePatchPortfolio.ts
  client/src/hooks/usePostPortfolio.ts
  client/src/pages/EditPortfolio.tsx
Labels: 📬API, 🔥Feature, 🛠Refector

#203 feat: 상세페이지 조정
  client/src/api/client.ts
  client/src/components/Detail/Comment.style.ts
  client/src/components/Detail/CommentItem.style.ts
  client/src/components/Detail/CommentItem.tsx
  client/src/components/Detail/DetailTitle.style.ts
  client/src/components/Detail/ProjectContent.style.ts
  client/src/components/Detail/ProjectImg.style.ts
  client/src/components/Detail/ProjectImg.tsx
  client/src/components/SignUp/SignInput.style.ts
  client/src/components/SignUp/SignInput.tsx
  client/src/components/SignUp/SignupForm.style.ts
  client/src/components/SignUp/SignupForm.tsx
  client/src/hooks/usePostCheckEmail.ts
  client/src/pages/Detail.tsx
  client/src/types/index.ts
Labels: 📬API, 🔥Feature

#206 design: CSS 수정
  client/src/components/User/CommentContainer.style.ts
  client/src/components/User/CommentContainer.tsx
  client/src/components/User/CommentItem.style.ts
  client/src/components/User/CommentItem.tsx
  client/src/components/User/Portfolio.tsx
  client/src/components/User/UserBasicInfo.style.ts
  client/src/components/User/UserBasicInfo.tsx
  client/src/components/User/UserInfo.tsx
  client/src/hooks/useGetUserPortfolios.ts
  client/src/store/slice/editUserProfileSlice.ts
  client/src/types/index.ts
Labels: 🎨HTML&CSS

#208 feat: 레이아웃 및 기능 전체 수정
  client/src/components/Detail/Comment.style.ts
  client/src/components/Detail/Comment.tsx
  client/src/components/Detail/CommentItem.style.ts
  client/src/components/Detail/CommentItem.tsx
  client/src/components/Detail/Description.style.ts
  client/src/components/Detail/DetailTitle.style.ts
  client/src/components/Detail/LikeBtn.style.ts
  client/src/components/Detail/LikeBtn.tsx
  client/src/components/Detail/ProjectContent.style.ts
  client/src/components/Detail/ProjectImg.style.ts
  client/src/components/Home/Banner.style.ts
  client/src/components/Home/Banner.tsx
  client/src/components/Login/LoginContainer.style.tsx
  client/src/components/Login/LoginContainer.tsx
  client/src/components/Portfolio/ImgBox.style.ts
  client/src/components/Portfolio/PortfolioContainer.style.ts
  client/src/components/Portfolio/TagBox.style.ts
  client/src/components/Portfolio/TextareaBox.style.ts
  client/src/components/Portfolio/UserBox.style.ts
  client/src/components/User/CommentContainer.style.ts
  client/src/components/User/UserBasicInfo.style.ts
  client/src/components/User/UserEditForm.style.ts
  client/src/layout/header/Hamburger.style.tsx
  client/src/layout/header/Header.style.tsx
  client/src/pages/AddEmail.style.ts
  client/src/pages/SignUp.style.ts
Labels: 🐞BugFix, 🔥Feature, 🎨HTML&CSS

#209 feat: addEmail 중복확인 및 접근 처리 기능 구현
  client/src/components/Login/LoginContainer.tsx
  client/src/pages/AddEmail.tsx
  client/src/router.tsx
Labels: 📬API, 🔥Feature

#210 feat: 유저 댓글 비밀글 적용
  client/src/api/client.ts
  client/src/components/User/CommentContainer.style.ts
  client/src/components/User/CommentContainer.tsx
  client/src/components/User/CommentItem.style.ts
  client/src/components/User/CommentItem.tsx
  client/src/components/User/Portfolio.tsx
  client/src/components/User/UserBasicInfo.tsx
  client/src/hooks/usePostUserComment.ts
  client/src/types/index.ts
Labels: 🐞BugFix, 🔥Feature

#213 feat: 기술스택 검색 기능 추가, 배너 일러스트 추가, 파비콘 추가
  client/public/assets/image/Meeting.svg
  client/public/index.html
  client/src/api/client.ts
  client/src/components/About/LandingSection.style.ts
  client/src/components/About/LandingSection.tsx
  client/src/components/Home/Banner.style.ts
  client/src/components/Home/Banner.tsx
  client/src/components/Home/Search.style.ts
  client/src/components/Home/Search.tsx
  client/src/components/Home/Sort.tsx
  client/src/components/Home/skillsData.ts
  client/src/hooks/useAuth.ts
  client/src/hooks/useGetPortfolioList.ts
  client/src/pages/Home.style.ts
  client/src/pages/Home.tsx
Labels: 📬API, 🔥Feature, 🎨HTML&CSS

#214 refactor: 중복 확인 버튼 수정
  client/src/pages/AddEmail.style.ts
  client/src/pages/AddEmail.tsx
Labels: 🛠Refector

#216 feat: 유저 댓글 작성시 로그인 확인
  client/src/components/User/CommentContainer.style.ts
  client/src/components/User/CommentContainer.tsx
  client/src/components/User/UserDetailInfo.style.ts
Labels: 🔥Feature, 🎨HTML&CSS

#217 feat: 상세 페이지 댓글 기능 수정 및 페이지네이션 기능 추가
  client/src/api/client.ts
  client/src/components/Detail/Comment.style.ts
  client/src/components/Detail/Comment.tsx
  client/src/components/Detail/CommentItem.tsx
  client/src/components/Detail/CommentPageBtn.style.ts
  client/src/components/Detail/CommentPageBtn.tsx
  client/src/components/Detail/DetailTitle.tsx
  client/src/components/Detail/ProjectImg.style.ts
  client/src/hooks/useDeletePortfolioComment.ts
  client/src/hooks/useGetPortfolio.ts
  client/src/hooks/useGetPortfolioComment.ts
  client/src/hooks/useLikeBtn.ts
  client/src/hooks/usePatchPortfolioComment.ts
  client/src/hooks/usePostPortfolioComment.ts
  client/src/pages/Detail.tsx
  client/src/types/index.ts
Labels: 🐞BugFix, 🔥Feature

#218 fix: 회원탈퇴 오류 수정
  client/src/components/User/UserEditForm.tsx
  client/src/hooks/useDeleteUserProfile.ts
Labels: 🐞BugFix

#224 fix: 전달되는 변수명 수정
  client/src/components/User/Portfolio.tsx
Labels: 🐞BugFix

#231 fix: 검색 옵션이 데스크탑일때와 모바일/태블릿일때 달라지는 버그 수정
  client/src/components/Home/Search.tsx
  client/src/hooks/useGetPortfolioList.ts
  client/src/pages/Home.tsx
Labels: 🐞BugFix

#238 fix: 유저페이지 포트폴리오 무한스크롤 오류 해결
  client/src/components/User/Portfolio.tsx
  client/src/hooks/useGetUserPortfolios.ts
  client/src/hooks/useInfiniteScroll.ts
Labels: 🐞BugFix

#239 실물 배포 v1.0.1
  client/src/components/Home/Search.tsx
  client/src/components/User/Portfolio.tsx
  client/src/hooks/useGetPortfolioList.ts
  client/src/hooks/useGetUserPortfolios.ts
  client/src/hooks/useInfiniteScroll.ts
  client/src/pages/Home.tsx
Labels: 🌏Deploy

#243 chore: github,google 로그인 url 변경
  client/src/api/client.ts
  client/src/hooks/usePatchPortfolio.ts
  client/src/hooks/usePostPortfolio.ts
Labels: 🌏Deploy

#245 docs: 프로젝트 정보 및 소개 문서 작성
  README.md
Labels: 📃Docs

#246 feat: 포트폴리오 삭제 시 즉시 적용
  client/src/components/Detail/DetailTitle.tsx
  client/src/hooks/useDeletePortfolio.ts
Labels: 📬API

#248 design: 전반적인 레이아웃 수정
  client/src/api/client.ts
  client/src/components/Detail/ProjectImg.tsx
  client/src/components/SignUp/SignupForm.style.ts
  client/src/components/SignUp/SignupForm.tsx
  client/src/layout/header/Hamburger.style.tsx
  client/src/layout/header/Header.style.tsx
  client/src/pages/Detail.style.ts
  client/src/pages/Detail.tsx
  client/src/utils/IncreasePageView.ts
Labels: 🐞BugFix, 🔥Feature, 🎨HTML&CSS

#249 feat:댓글 navbtn 숨기기 기능 추가
  client/src/components/Detail/Comment.tsx
Labels: 🐞BugFix, 🎨HTML&CSS

#250 fix:console 제거
  client/src/components/Detail/Comment.tsx
Labels: 🐞BugFix

#251 feat: 유저 댓글 무한스크롤 적용
  client/src/api/client.ts
  client/src/components/User/CommentContainer.style.ts
  client/src/components/User/CommentContainer.tsx
  client/src/components/User/CommentItem.tsx
  client/src/components/User/CommentsOfUser.tsx
  client/src/components/User/CommentsToPortfolio.tsx
  client/src/components/User/CommentsToUser.tsx
  client/src/components/User/UserInfo.style.ts
  client/src/hooks/useCommentsInfiniteScroll.ts
  client/src/hooks/useGetCommentsToPortfolio.ts
  client/src/hooks/useGetCommentsToUser.ts
  client/src/hooks/useGetUserComment.ts
  client/src/types/index.ts
Labels: 🔥Feature

#256 feat:회원가입 글자 수 제한 기능 추가
  client/src/components/SignUp/SignupForm.tsx
Labels: 🔥Feature
